version: '3.1'
services:
  app:
    container_name: docker-example
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo2
    image: mongo
    ports:
      - '27017:27017'